### ISSUE TITLE
Modeling coercions

### ISSUE THREAD

**Issue by leodasvacas** [rust-lang/chalk#104]
A description of what coercions do can be found in [the reference](https://doc.rust-lang.org/reference/type-coercions.html) and [the nomicon](https://doc.rust-lang.org/nightly/nomicon/coercions.html). 

In many places Rust only requires that one type coerces to another, but there is no way to explain that to the inference engine which only understands type equality. So if there are multiple types being coerced to a  single target type the current rustc implementation will sometimes greedily unify the first type it sees.

First a trivial example, in `let mut a = &&0; a = &0;` the type of `a` should be inferred to `&i32` not `&&i32`. It's the same with generic functions:

```rust
fn foo<T>(_: T, _: T) {}

fn main() {
    let x: u8 = 0;
    foo(&&x, &x); // Fails, `T = &&u8`.
    foo(&x, &&x); // Works, `T = &u8`.
}
```

And closures, here with `&mut` to `&` coercions:

```rust
fn main() {
    let mut a = 0;
    let b = 0;
    let c = |x| {};
    // Fails because c is inferred to Fn(&mut i32),
    // but works if lines below swapped and c is inferred to Fn(&i32).
    c(&mut a);
    c(&b);
}
```

For some cases rustc already improves on this with special treatment for coercing many expressions to a single target type (see `CoerceMany` in `coercion.rs` for details), so for example both `if true { &0 } else { &&0 }` and `if true { &&0 } else { &0 }` will work with resulting type `&i32`.

If we can model a  "`T` coerces to `U`" relationshig in chalk it would be a major step towards improving the situation and integrating coercions within the inference engine. Before diving into formulations for Chalk, I'll try to put together a description of how the current rustc code handles this in [coercion.rs](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/coercion.rs).

**Comment by nikomatsakis** [comment]
Closing this for now, since I think modeling coercions ought to be left for future work.
