### ISSUE TITLE
A deref obligation

### ISSUE THREAD

**Issue by leodasvacas** [rust-lang/chalk#105]
Deref is not well integrated into typeck, all derefs must be eagerly checked causing problems even in a simpe program such as:
```rust
use std::sync::Arc;

fn main() {
    let mut a = Default::default();
    // Works if the lines are swapped.
    let b = *a;
    a = Arc::new(0);
}
```
The type of `a` will not be inferred because derefs error if they find a type variable. There are probably good reasons of why this difficult to support, but hopefully chalk has a better chance at supporting derefs as obligations. I'll start by implementing `Deref` as domain goal.

**Comment by nikomatsakis** [comment]
Closing this for now. I think handling coercions is probably pretty squarely future work.
