### ISSUE TITLE
simplified crate reorg

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#214]
After pondering the comments by @matklad and others in our discussion, I propose the following crate organization. The idea is to merge the chalk-solve and chalk-rules crate, so that outside code only needs to instantiate a `Solver` with a `RustIrDatabase` (sometimes that supplies rust-ir), and everything else is handled internally to the `chalk-solve` crate. This seems simpler to explain and deal with than today's setup, but it has one downside: if we ever wanted to have rustc incorporate the chalk-rules logic directly, we would either have to tease the two crates apart again (which requires some traits in between) or else port rustc to use chalk-ir.

## Overview and end-goal

The chalk-solve crate would expect to be given a `RustIrDatabase`, which would be roughly equivalent to today's [`RustIrSource`]. It would allow you to instantiate a [`Solver`], just as today. Unlike today, though, [the `solve` method][sm] would not take a `&dyn ChalkSolveDatabase` but rather a `&dyn RustIrDatabase`. The implementation of the methods that are in `ChalkSolveDatabase` today would be moved and hardcoded into chalk-solver itself. So basically the idea is "give me some rust source, and I'll give you a trait solver".

[`RustIrSource`]: https://github.com/rust-lang/chalk/blob/eb1ed91c944b8e4f12b36299b3692b357724f596/chalk-rules/src/lib.rs#L21-L64
[`Solver`]: https://github.com/rust-lang/chalk/blob/eb1ed91c944b8e4f12b36299b3692b357724f596/chalk-solve/src/solve.rs#L95-L101
[sm]: https://github.com/rust-lang/chalk/blob/eb1ed91c944b8e4f12b36299b3692b357724f596/chalk-solve/src/solve.rs#L104-L126

Currently, the chalk-solve code doesn't know about the `RustIrDatabase` directly -- it instead has a `ChalkSolveDatabase` trait with some callbacks. These are implemented by the `chalk` crate, which then delegates to the code in chalk-rules. The idea here is to "cut out the middleman" and have chalk-solve directly invoke chalk-rules. (To add extra fun, the chalk-rules code sometimes needs to invoke chalk-solve, which is why we want to merge them into one crate.)

## Intermediate steps

If we merge the two crates into one, I think the steps would be roughly like this:

- [x] Rename `chalk_rules::RustIrSource` to `RustIrDatabase`
- [x] Copy-and-paste the code from chalk-rules into chalk-solve, replacing `ChalkRulesDatabase` with `ChalkSolveDatabase`. So you would have `trait ChalkSolveDatabase: GoalSolver + RustIrDatabase`.
- Remove the `is_coinductive` method from `ChalkSolveDatabase` and implement it directly in chalk-solve.
- [x] Instead of having the chalk-rules code (the code in coherence/wf) use the `GoalSolver` trait, make it require two parameters: a `db: &impl ChalkSolveDatabase` and a `SolverChoice`. It can then instantiate the `SolverChoice` into a solver itself (this is actually how that code used to work before I refactored it).
- [x] Remove the `GoalSolver` trait -- we probably want to keep the `ChalkDatabase` type having a `solve` method just like it does today, it just wouldn't implement `GoalSolver`, it would be an inherent method
- [ ] Remove the `program_clauses_that_could_match` method and replace it with the more targeted code from rustc (see below)
- [ ] At this point the `ChalkSolveDatabase` trait is just a thin wrapper for `RustIrDatabase`, so remove it and have only `RustIrDatabase`
- [ ] Done!

## How `program_clauses_that_could_match` should work

Right now, the implementation of `program_clauses_that_could_match` is quite naive. It touches and accesses all the impls from all the traits:

https://github.com/rust-lang/chalk/blob/eb1ed91c944b8e4f12b36299b3692b357724f596/src/db.rs#L66-L86

What we should *eventually* be doing is to port over the code from rustc that handles this case. This basically examines the goal and uses a bit of knowledge of lowering to figure out what bits of rust-ir might be relevant: it would then invoke the [`to_program_clauses`] method on just those bits of rust-ir to construct the result. (This is a bit complex for `FromEnv` goals etc; maybe @scalexm can give the right points into the rustc source, actually, or else I'll go find them later.)

[`to_program_clauses`]: https://github.com/rust-lang/chalk/blob/eb1ed91c944b8e4f12b36299b3692b357724f596/chalk-rules/src/clauses.rs#L9-L14

**Comment by mark-i-m** [comment]
Hi @nikomatsakis ! When you have time, could you take a quick look over https://github.com/rust-lang/rustc-guide/pull/298 (sorry if this is the wrong place to post). The reorganization has broken a lot of links in rustc-guide.

**Comment by nikomatsakis** [comment]
I [left some notes on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/chalk.20crates/near/163509324) as to what it would mean if we just merged the chalk-solve and chalk-rules crates -- in particular what the transition plan would be. I'm sort of leaning that way, on the basis of "simpler is better".

**Comment by nikomatsakis** [comment]
I updated the main comment to a newer, simpler proposal. The history of [this gist](https://gist.github.com/nikomatsakis/ae7b129b025f730952da891eee652711) logs the older proposal.

**Comment by nikomatsakis** [comment]
(Note: I think @detrumi is working on this.)

**Comment by nikomatsakis** [comment]
@mark-i-m we probably just broke a whole bunch of links again =)

**Comment by mark-i-m** [comment]
Does it make sense to just wait until the refactoring subsides or will that take a long time?

**Comment by nikomatsakis** [comment]
@mark-i-m there is one more step, I guess we might as well wait for that

**Comment by nikomatsakis** [comment]
I was planning on -- once this is done -- trying to do a rustc-guide chapter on the final setup anyway

**Comment by detrumi** [comment]
This issue can probably be closed now, since the last two steps have been completed.

**Comment by mark-i-m** [comment]
Before you do, could you please update the broken links in the rustc-guide chapter?

**Comment by nikomatsakis** [comment]
This is done!
