### ISSUE TITLE
improve test organization

### ISSUE THREAD

**Issue by detrumi** [rust-lang/chalk#224]
Currently, the main Chalk is mainly an elaborate testing harness, which should be moved to a different crate. The tests themselves should then probably be moved to a `tests` directory.

First, clear out the main crate:
- [ ] Move the tests and test helpers to a new testing crate
- [ ] Move the repl (`chalki`) to its own crate
- [ ] Make `chalk-solve` the main crate (and call it `chalk`)

Then, organize the tests:
- [ ] Move tests to a `tests` directory
- [ ] Separate tests into categories
- [ ] Test improvements? (maybe use insta snapshots?)

**Comment by matklad** [comment]
I'll also through in an idea of using test coverage marks: 

https://github.com/rust-analyzer/rust-analyzer/blob/ef782adc293deb287128f005dbab2038ba3ccdc1/crates/test_utils/src/marks.rs

**Comment by nikomatsakis** [comment]
This is basically fixed by #271

**Comment by nikomatsakis** [comment]
Closing this as fixed, I moved the test coverage idea to #278.
