### ISSUE TITLE
Re: Where does the name come from?

### ISSUE THREAD

**Issue by Kinrany** [rust-lang/chalk#232]
> **Where does the name come from?** `chalk` is named after Chalkidiki, the area where Aristotle was born. Since Prolog is a logic programming language, this seemed a suitable reference.

Before I read this part of the README, I was sure `chalk` was named after [chalk]!

I think `chalk` is a cool name because [chalk] is a material (which makes it conceptually related to rust) and is commonly used for expressing thoughts on a blackboard.

Just wanted to share that the real etymology was surprising. Feel free to close this issue :)

[chalk]: https://en.wikipedia.org/wiki/Chalk

**Comment by nikomatsakis** [comment]
I did have connotations of blackboards in mind, too :)
