### ISSUE TITLE
coinduction impl fails to consider that recursive calls may later fail

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#248]
Today's handling of coinduction in the logic engine is unsound. We consider any purely coinductive loop to be true, but actually a coinductive loop could fail later on.

Consider something like this, where each C*i* is a coinductive goal:

```
C1 :- C2, C3.
C2 :- C1.
```

Here, C1 is clearly false, because there is no rules for C3. Therefore, C2 must also be false. However, under certain conditions our current code will incorrect consider that `C2` holds.

**Comment by nikomatsakis** [comment]
This is where the bug in our logic lies:

https://github.com/rust-lang/chalk/blob/457b473bf34a889fce709c44ac870125f018775c/chalk-engine/src/logic.rs#L1061-L1086

We assume that a recursive, coinductive goal is successful -- but in fact we should make the result *conditional* on that recursive, coinductive goal. This is effectively a form of delayed goal.

**Comment by nikomatsakis** [comment]
My plan for the fix, in short:

* If you see a co-inductive cycle, we create an answer with a delayed literal
    * So in our example, proving C2 would result in an answer "Yes, if C1"
* This delayed literal would propagate forward, so C1 would wind up with answer "Yes, if C1"
    * At this point, we can drop the delayed literal 
* Meanwhile if we start another query (say of C2) and we get the answer "Yes, if C1", we would have to also do the query C1 to see if the result is yes or no

I've not worked out all the details here to figure out how easy/hard this will be -- but it's a simpler form of delayed literals than what we used to have, I think.

One concern I have is that the resulting answer will depend on the table you start with.

**Comment by jackh726** [comment]
So, I've been looking through the code for this, and the reason the added tests are failing are because C1, C2, and C3 are auto traits. And there isn't a mechanism at all to say "yes, C1 is an auto trait, but in this case it isn't"

**Comment by jackh726** [comment]
So, I think the rules for how auto traits behave with explicit impls here need to be better defined (or at least defined for me, since I don't know them). 

What is surprising to me is that the second test's output doesn't match the first one. So there's more to this for sure.

**Comment by jackh726** [comment]
Ok @nikomatsakis 

The good news is I have a fix. However, it's quite a bit overengineered and I think most of what I changed is unnecessary. So I'll spend time tomorrow un-overengineering it.
