### ISSUE TITLE
remove support for "negative cycles"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#250]
Chalk today correctly handles "negative cycles", where you have something like

```
A :- not { B }.
B :- not { A }.
```

in the underlying logic. This requires a fairly complex mechanism called *delayed literals*. It is also, I believe, unnecessary for Rust -- and that should probably be a continued design goal. 

The reason to remove this logic is two-fold:

- It is quite complicated. It requires us to "delay" goals and then find a good time to "undelay" them, and it is hard to know when the right time for that is.
- It complicates fixing rust-lang/chalk#248, which probably requires a similar mechanism.

The only reason that we might need this would be specialization, which uses `not { }` reasoning in a more general way that could in principle recurse. However, we are guaranteed that it doesn't because we require an acyclic relationship between traits (at least at present), such that if impl A (for trait T) overrides another impl, the where clauses in A must not require solving anything from the trait T. So you should not get any sort of cycle.

**Comment by nikomatsakis** [comment]
I talked to @tmandry and they're going to take a swing at this

**Comment by nikomatsakis** [comment]
Or not! Looks like @jackh726 is on it ;)

**Comment by jackh726** [comment]
The timing!
