### ISSUE TITLE
simplify chalk context trait and logic-engine

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#255]
When integrating chalk into rustc, we had to make a number of changes to account for the `'gcx` / `'tcx` lifetime split, but that split no longer exists. 

Some of the things we can simplify:

We no longer need to canonicalize when "storing" strands into the table, so we should be able to get rid of the `CanonicalStrand` type:

https://github.com/rust-lang/chalk/blob/13303bb0067c6ed0572322080ae367ee38f9e7c9/chalk-engine/src/strand.rs#L6-L12

Similarly, I don't think we need the whole "with_instantiated_foo" workarounds here:

https://github.com/rust-lang/chalk/blob/13303bb0067c6ed0572322080ae367ee38f9e7c9/chalk-engine/src/context.rs#L179-L202

It's going to take a bit of playing around to reconstruct the simplified structure though.

**Comment by jackh726** [comment]
@nikomatsakis I've been playing with this over the weekend and have made a lot of progress. Still have some more work to do, but should have a PR sometime soon.

**Comment by jackh726** [comment]
I'm gonna go ahead and close this. There *might* be room for simplification here. But the code has diverged so much from what it was when these changes were made, it's not clear if and what it is.
