### ISSUE TITLE
Discord channel mentioned in README is gone (?)

### ISSUE THREAD

**Issue by ineol** [rust-lang/chalk#256]
The Readme says:

> If you're like to contribute, consider joining the [Traits Working Group](https://github.com/rust-lang/rust/issues/48416). We hang out on the [rust-lang discord](http://discord.gg/rust-lang) in the `#wg-traits` channel (Lang category).

but it seems like this is not the case anymore. More generally, I could not find out the current status of the new rustc trait implementation.

**Comment by nikomatsakis** [comment]
It's true, that's out of date. We mostly hang out on Zulip now. I'll try to update "all the things"

**Comment by nikomatsakis** [comment]
More canonical link

https://rust-lang.github.io/compiler-team/working-groups/traits/

though it too is somewhat out of date :)
