### ISSUE TITLE
Make chalk_solve::Solver UnwindSafe

### ISSUE THREAD

**Issue by matklad** [rust-lang/chalk#260]
In rust-analyzer, we use panics to implement cancellation. That means that, while we use chalk to solve some goal, the callbacks from chalk into rust-analyzer might panic, unwinding past the Solver.

This unfortunately leaves the solver in an inconsistent state at the moment. See https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/Logic.20panics for some more details. 

This issue has been assigned to @marmeladema via [this comment](https://github.com/rust-lang/chalk/issues/260#issuecomment-616114664).

**Comment by matklad** [comment]
Note that we now try to catch panics within the chalk itself, to make rust-analyzer more robust:

https://github.com/rust-analyzer/rust-analyzer/pull/2818

At the moment, we just reset chalk's state on panic, but it would be more convenient if chalk always was consistent after a panic.

**Comment by jackh726** [comment]
With #338 merged, closing this only requires some regression tests for panic safety. This is pretty easy, so I'll mark it as such.
