### ISSUE TITLE
add a "well-known" Sized trait to `chalk_solve`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#261]
I think the `chalk-solve` crate ought to start encoding rules for "well-known" traits that require compiler support. A good place to start is the `Sized` trait. I'm opening this issue to remember the problem, it will be extended with mentoring instructions.

**Comment by lqd** [comment]
That's `chalk-solve`, right ?

**Comment by nikomatsakis** [comment]
Blocked on #356

**Comment by nikomatsakis** [comment]
So I think what we want here has two parts:

* First of all, we want to extend the 'well formedness' rules for *struct definitions* -- structs are not permitted to have "unsized fields" except in specific locations (notably, only the final field may be unsized). (Furthermore, *enums* are not permitted to have to unsized members...at all?)
* Based on this, rustc's code for checking whether a struct type is sized is quite specialized (important since this is a very common check) and it looks only at the final field of a struct. This may even have been *necessary* to prevent some kinds of cycles, I have a dim memory of that.

Some links from rustc code:

* [`adt_sized_constraint`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ty/ty/fn.adt_sized_constraint.html), [`sized_constraint_for_ty`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ty/ty/fn.sized_constraint_for_ty.html) -- these functons are kind of minimally documented, but the basic idea is that given a type T, they return a type U such that `T: Sized` if `U: Sized`. 
* [the code in rustc that checks that a struct/enum/union's fields are sized](https://github.com/rust-lang/rust/blob/75208942f6144daac669e8e382029fc33bdce841/src/librustc_typeck/check/wfcheck.rs#L383-L404)

**Comment by Areredify** [comment]
I'll take this one

**Comment by Areredify** [comment]
blocked on #368

**Comment by marmeladema** [comment]
I hope https://github.com/rust-lang/chalk/pull/413 will help with this issue.

**Comment by jackh726** [comment]
This is done :) existing types have this logic and new types get it added in
