### ISSUE TITLE
Remove dependency on lalrpop-intern

### ISSUE THREAD

**Issue by matklad** [rust-lang/chalk#287]
Salsa uses `lalrpop-intern` internally for string interning. However, `lalrpop-intern` is not thread safe: its IDs are `Send`, but the interner is stored in a thread-local. 

cc @flodiebold : I remember discussing this issue before, have we just forgotten about this?

**Comment by jackh726** [comment]
I'm actually going to mark this as a good first issue. It shouldn't be *too* difficult. There was some discussion in the closed PR: https://github.com/rust-lang/chalk/pull/295#issuecomment-562770319

**Comment by jackh726** [comment]
This should have been closed in https://github.com/rust-lang/chalk/pull/336. I linked the wrong issue.
