### ISSUE TITLE
test-random takes ages to check

### ISSUE THREAD

**Issue by matklad** [rust-lang/chalk#298]
Today I've noticed that this function takes two minutes to type-check in rust-analyzer:

```rust
    fn test_random() {
        // not sure how to test this aside from just getting some values
        let _n : usize = random();
        let _f : f32 = random();
        let _o : Option<Option<i8>> = random();
        let _many : ((),
                     (usize,
                      isize,
                      Option<(u32, (bool,))>),
                     (u8, i8, u16, i16, u32, i32, u64, i64),
                     (f32, (f64, (f64,)))) = random();
    }
```
https://github.com/rust-random/rand/blob/c388cb2d109e99afc3a48e0bbf90d15085e86156/src/lib.rs#L686-L697

I haven't investigated this further, but I think the most likely cause is some exponential blow up in chalk. cc @flodiebold

**Comment by detrumi** [comment]
This is not slow any more, so I'm closing this.
