### ISSUE TITLE
Non-ambigous answer that can replace an ambiguous answer may panic

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#302]
It's possible that a new answer may not be ambiguous, but an older answer was. In this case `push_answer` on `Table` does not insert a new answer, but still returns `true`. https://github.com/rust-lang/chalk/blob/3ef20308e7882a3e5fb71a6f28caab8cc71cf5f0/chalk-engine/src/table.rs#L107

However, if `true` is returned, then it's propagated up and eventually the `AnswerIndex` is incremented
https://github.com/rust-lang/chalk/blob/3ef20308e7882a3e5fb71a6f28caab8cc71cf5f0/chalk-engine/src/forest.rs#L231

Then, in the next iteration of checking for an answer, the `AnswerIndex` is not the next index, so this assertion can fail:
https://github.com/rust-lang/chalk/blob/3ef20308e7882a3e5fb71a6f28caab8cc71cf5f0/chalk-engine/src/logic.rs#L194 

Simply changing `push_answer` to panic whenever a new answer would replace an old one doesn't cause any tests to fail. So if this is a valid case, then a test should be added.

Relevant zulip: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/design.20meeting.202019.2E12.2E02/near/182380076

**Comment by lnicola** [comment]
This causes a panic when running `rust-analyzer` over itself, as seen in https://github.com/rust-analyzer/rust-analyzer/issues/2675.

**Comment by jackh726** [comment]
@lnicola Thanks for the report. It would be nice to get min repro for this, but I'll start looking at a fix.

**Comment by jackh726** [comment]
This can also be reproduced with the existing test `gat_unify_with_implied_wc` with a `max_size` of `3`.

**Comment by jackh726** [comment]
This was fixed in #433
