### ISSUE TITLE
Potential bug: `should have floundered`

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#318]
Running the existing `forall_projection_gat` test with a `max_size` of `3` causes a panic with `should have floudered`, which comes from this line https://github.com/rust-lang/chalk/blob/4005b5ff3ee31a197ee3aa7d0c97d670cee0067b/chalk-solve/src/clauses.rs#L346. While using a `max_size` that low usually won't happen, it indicates that logic somewhere is wrong.

**Comment by Mcat12** [comment]
I no longer see a `should have floundered` panic with this test case, although several goals no longer have inference guidance.

**Comment by jackh726** [comment]
This was a bit nebulous to begin with. I'm gonna close.
