### ISSUE TITLE
Extend `TypeFamily` with some context

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#328]
The various `intern` methods on `TypeFamily` do not currently permit any context. See e.g. [`intern_ty`]. We want that to take an `&self` parameter. This is going to be a somewhat extensive refactoring, however, because it's going to require threading a value around so that we can invoke the methods on it.

[`intern_ty`]: http://rust-lang.github.io/chalk/chalk_ir/family/trait.TypeFamily.html#tymethod.intern_ty

**Comment by nikomatsakis** [comment]
Proposed design to start is this. We will move from

```rust
trait TypeFamily {
    type InternedType;
    ...

    fn intern_ty(data: TyData<Self>) -> Self::InternedType;
    fn ty_data(ty: &Self::InternedType) -> &TyData<Self>;
}
```

to

```rust
trait TypeFamily {
    type InternedType;
    ...

    fn intern_ty(&self, data: TyData<Self>) -> Self::InternedType;
    fn ty_data(ty: &Self::InternedType) -> &TyData<Self>;
}
```

Note that I left `ty_data` alone -- I do expect to add `&self` there too, but not as part of *this* issue. We'll do that next. Also, I only talked about types, but eventually we'll want to add this to all the other sorts of interned things. But the first step will be the hardest.

**Comment by yaahc** [comment]
Indirectly related but we renamed TypeFamily to Interner here

https://github.com/rust-lang/chalk/pull/329

**Comment by nikomatsakis** [comment]
This was done in #330
