### ISSUE TITLE
Adapt Chalk's debruijn indices to rustc's debruijn indices

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#334]
In Chalk, we assign a distinct debruijn index to every variable in a binder. In Rustc, debruijn indices identify the *binder* but we use a separate index for the variable *within* the binder. So, `for<'a, 'b>` in Chalk would introduce two debruijn indices, but in rustc only one. We should make these line up, and it's easier to adapt to the rustc model (plus that model has some advantages, in terms of making things a bit simpler from the code perspective).

**Comment by GabrielMajeri** [comment]
I've noticed @nikomatsakis is assigned to this, is this issue open for outside contribution?

**Comment by nikomatsakis** [comment]
This is done :)
