### ISSUE TITLE
Use `tracing` library for debugging and possibly benchmarking

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#337]
Currently, there is a simple debugging framework (if you can call it that) in `chalk-macros`. Implementing `tracing` support could allow fancy debugging or benching, such as following a `Strand`.

cc. @davidbarsky

This issue has been assigned to @nolanderc via [this comment](https://github.com/rust-lang/chalk/issues/337#issuecomment-618070128).

**Comment by davidbarsky** [comment]
@jackh726 I'll be able to pick this up this sprint. As we discussed copying over our discussion from wg-traits:


> **David Barsky**: looked a bit at strands in chalk-engine (cc: @Jack Huey). I think if I were place tracing _anywhere_ in chalk, it'd be in here, alongside the timestamp: https://github.com/rust-lang/chalk/blob/master/chalk-engine/src/strand.rs#L13. it'd be a bit similar to how tracing-futures work, minus the feature flags and annotations: https://github.com/tokio-rs/tracing/blob/master/tracing-futures/src/lib.rs#L223-L230
> **David Barsky**: I the "entry" of the span (for tracking work) could occur at strand activation here: https://github.com/rust-lang/chalk/blob/master/chalk-engine/src/table.rs#L83
> **David Barsky**: at least some closure would happen here: https://github.com/rust-lang/chalk/blob/master/chalk-engine/src/table.rs#L120
> **David Barsky**: Chalk engine is also more approachable than I thought! Kudos to whoever wrote the docs.
> **Jack Huey**: I think that mostly sounds good to me
> **Jack Huey**: I think I would be the entry for a span here: https://github.com/rust-lang/chalk/blob/af48f302a1f571b3ca418f7c5aa639a144a34f75/chalk-engine/src/logic.rs#L173
> **Jack Huey**: But also curious what your thoughts are on have a Table having a span
> **Jack Huey**: (in addition to Strand)
> **Jack Huey**:
> > Chalk engine is also more approachable than I thought! Kudos to whoever wrote the docs.
> 
> The docs indeed have been quite solid, even since I first started with chalk. When I refactored to make it iterative, I made it a point to even more thoroughly document it. So I'm glad you found them helpful
> **David Barsky**: I think table can have a span, there's a pattern where we have a "server" span in asynchronous servers
> **David Barsky**: yeah, I think that's a good spot to put span entry.
> **David Barsky**: now, if I wanted to _run_ chalk engine and emit this data, what would the best way to do that be?
> **David Barsky**: lemme look, actually. i think some sort of tests would be a good start.
> **David Barsky**: yeah, i think i can do something in the `test!` macro
> **Jack Huey**:
> yeah, i think i can do something in the `test!` macro
> Yeah, either the test! macro or the chalk REPL would be good places to start looking at how to run
> **Jack Huey**: (probably `test`)

**Comment by jackh726** [comment]
> @rustbot assign @nolanderc
This doesn't work unless you're in `wg-triage`

But @nolanderc, you can do `@rustbot claim`
