### ISSUE TITLE
extend lookup methods for things beyond types with `&self`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#341]
Building on https://github.com/rust-lang/chalk/issues/339 and https://github.com/rust-lang/chalk/issues/340, we should extend the `*_data` methods with `&self`:

* [x] [`lifetime_data`](http://rust-lang.github.io/chalk/chalk_ir/interner/trait.Interner.html#tymethod.lifetime_data) -- #349 
* [x] [`parameter_data`](http://rust-lang.github.io/chalk/chalk_ir/interner/trait.Interner.html#tymethod.parameter_data) -- #350
* [x] [`goal_data`](http://rust-lang.github.io/chalk/chalk_ir/interner/trait.Interner.html#tymethod.goal_data) -- #352 
* [x] [`goals_data`](http://rust-lang.github.io/chalk/chalk_ir/interner/trait.Interner.html#tymethod.goals_data) -- #353 
* [x] [`substitution_data`](http://rust-lang.github.io/chalk/chalk_ir/interner/trait.Interner.html#tymethod.substitution_data) -- #354 
* [ ] [refactor how we handle Debug impls to share code](https://github.com/rust-lang/chalk/pull/353#discussion_r394930949) -- #355

**Comment by Mcat12** [comment]
@nikomatsakis As of #355, this issue should be complete?

**Comment by nikomatsakis** [comment]
I think that's correct.
