### ISSUE TITLE
experiment with resurrecting the recursive solver

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#351]
We should experiment with returning to a "recursive style" solver in chalk. As described in [this gist](https://gist.github.com/nikomatsakis/bfbdbe588d6fc61ecb09e3b51847fb7c), recursive solving does offer some potential advantages:

* if we extend the setup, it may resolve the ambiguous associated type problem (ironic since we previously removed the recursive solver in part because we couldn't make it handle associated types well)
* less overall work, at the cost of completeness
* cleaner handling for multiple threads doing queries at once without locking (the cache is separated from the main solver stack)
* smoother integration into systems like chalk

Work items:

* [x] Initial PR 
* [ ] Coinduction semantics https://github.com/rust-lang/chalk/issues/399
* [ ] Invoke `program_clauses_for_goal` on the canonicalized form vs instantiating the goal first ([comment](https://github.com/rust-lang/chalk/pull/372#discussion_r408038753))

This issue has been assigned to @flodiebold via [this comment](https://github.com/rust-lang/chalk/issues/351#issuecomment-614047090).

**Comment by nikomatsakis** [comment]
@flodiebold is working on this

**Comment by jackh726** [comment]
Dang it that didn't work.

**Comment by jackh726** [comment]
I would say that the "experiment" is done. Any follow up issues (including #399) can just be separate.
