### ISSUE TITLE
extend `TraitDefn` with concept of "well-known trait" identifier

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#356]
In order to accomodate built-in traits, we first have to be able to identify them. The idea here is to extend `TraitDatum` with a kind of `well_known: Option<WellKnownTrait>` field. [I sketched an outline of how to do this on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/builtin.20traits/near/191539918).

**Comment by nikomatsakis** [comment]
@yaahc is I think going to look into this

**Comment by yaahc** [comment]
Sounds good, I'm assuming this will be a short issue to do so I'll hold off on starting with the `Sized` trait until you've got this landed.

**Comment by nikomatsakis** [comment]
@yaahc I was hoping you could do this work :)

**Comment by nikomatsakis** [comment]
That is, I think we can add it with `Sized` and maybe a few other traits but not really support them yet

**Comment by nikomatsakis** [comment]
Let me know if you don't have time though and I'll clear the assignment

**Comment by yaahc** [comment]
Oooo, I misread, i thought you said you were going to look into it. Lol okay yea I got this :+1:
