### ISSUE TITLE
Add ability to output a `.chalk` file for reproducing bugs

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#365]

**Comment by jackh726** [comment]
Initial PR merged: #430

There are some followup things in the review there.

**Comment by nikomatsakis** [comment]
Very cool

**Comment by jackh726** [comment]
Another thing that we should do is also be able to write out a goal

**Comment by jackh726** [comment]
Also, in #557, we now no longer error on printing placeholders, fn defs, and closures. These should actually print the right thing

**Comment by jackh726** [comment]
Also, when we record the goals too, then we won't have to rely on implementation details to ensure that items that are present in them actually get recorded (since we don't actually always need their `Datum` (see https://github.com/rust-lang/chalk/pull/566/files#r452485578))

**Comment by jackh726** [comment]
Gonna call this one closed, since the base implementation is done and my review comments seemed to have been addressed. Further bugs can be opened as new issues.
