### ISSUE TITLE
adopt synstructure for our custom derives

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#381]
Our custom derive code could maybe be made cleaner by using the `synstructure` crate -- but let's wait until we've landed https://github.com/rust-lang/chalk/pull/373/

This issue has been assigned to @Areredify via [this comment](https://github.com/rust-lang/chalk/issues/381#issuecomment-612322388).

**Comment by detrumi** [comment]
We should take inspiration from rustc: https://github.com/rust-lang/rust/blob/master/src/librustc_macros/src/type_foldable.rs

([discussion in Zulip](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/design.20meeting.202020.2E04.2E07/near/193247680))
