### ISSUE TITLE
Failed to install on musl system (aipine linux)

### ISSUE THREAD

**Issue by gspe** [rust-lang/chalk#388]
I'm trying to install rust-analyzer on alpine linux docker but the installation fail with this error:
```
error: failed to compile `rust-analyzer v0.1.0 (/rust/rust-analyzer/crates/rust-analyzer)`, intermediate artifacts can be found at `/rust/rust-analyzer/target`

Caused by:
  cannot produce proc-macro for `chalk-derive v0.1.0 (https://github.com/rust-lang/chalk.git?rev=039fc904a05f8cb3d0c682c9a57a63dda7a35356#039fc904)` as the target `x86_64-unknown-linux-musl` does not support these crate types
Error: install server

Caused by:
    0: process `cargo install --path crates/rust-analyzer --locked --force ` failed
    1: exit code: 101
```

**Comment by detrumi** [comment]
This is a rustc limitation, see [rust#40174](https://github.com/rust-lang/rust/issues/40174).
Proc macros are really convenient in chalk for deriving traits like `Fold`, so I don't think we'll be removing them.

**Comment by jackh726** [comment]
Unfortunately, I'm really not sure there's anything for us to do here. As @detrumi said, seems like a rustc issue.

Sorry 😟
