### ISSUE TITLE
Derive Zip impls

### ISSUE THREAD

**Issue by detrumi** [rust-lang/chalk#397]
We [already derive](https://github.com/rust-lang/chalk/blob/master/chalk-derive/src/lib.rs) `Fold` and `HasInterner` impls, we should do the same for [`Zip`](https://github.com/rust-lang/chalk/blob/master/chalk-ir/src/zip.rs#L72), which still uses some macros for that: [`eq_zip`](https://github.com/rust-lang/chalk/blob/master/chalk-ir/src/zip.rs#L180), [`struct_zip`](https://github.com/rust-lang/chalk/blob/master/chalk-ir/src/zip.rs#L205) and [`enum_zip`](https://github.com/rust-lang/chalk/blob/master/chalk-ir/src/zip.rs#L300)

This issue has been assigned to @zaharidichev via [this comment](https://github.com/rust-lang/chalk/issues/397#issuecomment-613830004).

**Comment by zaharidichev** [comment]
@detrumi so would that result in actually two deparate derives: 
- Zip (handles structs and enums)
- ZipEq (handles the eq_zip macro ?

**Comment by detrumi** [comment]
Calling it `derive(ZipEq)` could be confusing, since it's still the same trait that's being derived. But we still need to handle them differently, so maybe that's indeed the simplest solution.

**Comment by nikomatsakis** [comment]
You can just not handle the macro case, too, and leave that as a macro.

**Comment by nikomatsakis** [comment]
That's what we did in some other comparable cases, such as `copy_fold!`

**Comment by nikomatsakis** [comment]
That's probably what I would do to start.

**Comment by zaharidichev** [comment]
@detrumi  First time using synstructure here, but looking a bit more at it, it seems to me that this will not be as clean as the Fold derivation. Namely, instead of deconstructing a single type, we need to dconstruct a tuple of two types so .`each_variant` will not quite work in this situation.. Is there a cleaner approach that I am missing?

**Comment by detrumi** [comment]
If you look at the source of `each_variant`, you can see that it does a `for variant in &self.variants` loop. So you could probably do something like this:
```
for (field_a, field_b) in &a.variants.iter().zip(b.variants.iter()) { ... }
```
