### ISSUE TITLE
"Potentially incomplete links" found by book link checker

### ISSUE THREAD

**Issue by Mcat12** [rust-lang/chalk#425]
The link checker currently reports some warnings:
```
warning: Potential incomplete link

   ┌── what_is_chalk.md:5:18 ───
   │
 5 │ > [open an issue][rustc-issues] so we can fix it. If you are able to fix the
   │                  ^^^^^^^^^^^^^^ Did you forget to define a URL for `rustc-issues`?
   │
   = hint: declare the link's URL. For example: `[rustc-issues]: http://example.com/`
```
Source: https://github.com/rust-lang/chalk/pull/424/checks?check_run_id=634114550#step:5:16

Rendered example of a broken link:
![Screenshot from 2020-04-30 13-49-24](https://user-images.githubusercontent.com/4417660/80742924-28d13100-8aea-11ea-95e3-b77a941fe41d.png)

Should these warnings be increased to errors? All of the warnings currently correspond to broken links (2 in total, but the lint checker outputs duplicate warnings).

This issue has been assigned to @Mcat12 via [this comment](https://github.com/rust-lang/chalk/issues/425#issuecomment-626954678).

**Comment by Mcat12** [comment]
The broken links have been fixed, so the remaining issue is if similar future warnings should instead be errors.

**Comment by jackh726** [comment]
I would be okay if the warnings got bumped up to errors, since the link check is a separate check and isn't run on master. @Mcat12 do you want to do change this?
