### ISSUE TITLE
Remove dependency on lalrpop-intern

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#431]
This is a continuation of #287

Basically, `lalrpop-intern` is no longer maintained (it's actually missing in lalrpop master). In #336, we made it only be used in tests and `chalk-integration`. However, we should use a separate crate. (In #295, I converted to string_cache. I think we can probably just use most of this PR.)

This issue has been assigned to @Mcat12 via [this comment](https://github.com/rust-lang/chalk/issues/431#issuecomment-623183917).

**Comment by Mcat12** [comment]
I'm interested in contributing to chalk and this seems like a good issue to learn the code base with.

@rustbot claim

**Comment by Mcat12** [comment]
@nikomatsakis You made this comment on the closed PR; is there more refactoring requested? Or perhaps it can be handled in another issue?
> I think what I'd rather do is not (at least outside the AST) encode any specific string representation, instead moving that into the the context.

https://github.com/rust-lang/chalk/pull/295#issuecomment-562770319
