### ISSUE TITLE
extend chalk to include outlives goals

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#435]
As discussed in our meeting today, [starting around here](https://zulip-archive.rust-lang.org/144729wgtraits/54350designmeeting20200505.html#196364729), we want to extend chalk to handle region/type outlives goals and constraints to enable rustc integration. The steps are probably:

* add region outlives goals that generate region outlives constraints
* use region outlives goals in unification to simplify things
* add type outlives goals and constraints (and don't address the for for<'a> T: 'a thing)-
* connect to rustc

**Comment by jackh726** [comment]
I'm going to work a bit on the region outlives.

**Comment by rvolgers** [comment]
Just out of curiosity, would this end up solving https://github.com/rust-lang/rust/issues/25860 ?

**Comment by nikomatsakis** [comment]
Not directly. It's part of a larger plan that will address that problem, though.

**Comment by nathanwhit** [comment]
I've been doing some work on the type outlives goals/constraints.

**Comment by jackh726** [comment]
This is done now
