### ISSUE TITLE
create `TypeName` for `&` and `&mut`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#438]
As part of https://github.com/rust-lang/chalk/issues/368, we need to extend chalk's `TypeName` to model the built-in `&` and `&mut` types. We can add a variant `Ref(Mutability)`, where `Mutability` is a new type to add to chalk-ir based on [rustc's Mutability enum](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/enum.Mutability.html). 

You can follow https://github.com/rust-lang/chalk/pull/394 which provides a rough model of what needs to be extended. You probably want to model this on how tuples are handled, a N-ary tuple like `(_, _)` has two generic type parameters, and `&` and `&mut` have two generic parameters too (a lifetime and a type).

You would need to

* add `Ref(Mutability)` to `TypeName`
* extend parser to accept `&`, `&mut` types
* Update the [current state](http://rust-lang.github.io/chalk/book/clauses/well_known_traits.html#current-state) table to include the new types, I don't think it requires any special handling apart from `Sized`, I think its impls live in the standard library

This issue has been assigned to @nathanwhit via [this comment](https://github.com/rust-lang/chalk/issues/438#issuecomment-625616425).

**Comment by Mcat12** [comment]
> Update the current state table to include str, I don't think it requires any special handling apart from Sized, I think its impls live in the standard library

Is this a copy-paste error? It appears in #439 and #437 as well.

**Comment by jackh726** [comment]
I merged the PR a *bit* too early. `&mut` references aren't copy/clone. @nathanwhit
