### ISSUE TITLE
generalize the builtin struct type to adt to match rustc

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#453]
Chalk currently has a notion of [struct types](http://rust-lang.github.io/chalk/chalk_ir/enum.TypeName.html#variant.Struct) but rustc has the more general [adt](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/enum.TyKind.html#variant.Adt). Also, chalk expects a `DefId` but in rustc we use an `AdtDef` (a pointer to an interned structure).

We should align with rustc here:

* Rename `TypeName::Struct` to `TypeName::Adt`
* Rename `StructId<I>` to `AdtId<I>`
* Extend `Interner` trait to have `I::InternedAdtId` and adapt `AdtId<I>` to be a wrapper around `InternedAdtId` (instead of `I::DefId`, [as today](http://rust-lang.github.io/chalk/chalk_ir/struct.StructId.html))
* We can map `InternedAdtId` to the same type as `DefId` in our integration, rustc can use `&'tcx AdtDef`
* Rename [`StructDatum`](http://rust-lang.github.io/chalk/chalk_rust_ir/struct.StructDatum.html) and [`StructDatumBound`](http://rust-lang.github.io/chalk/chalk_rust_ir/struct.StructDatumBound.html) to use the `Adt` terminology -- we don't actually have to change the list of fields for now, though eventually we may want to do so to allow rustc to more cheaply give access from the `AdtDef`

This issue has been assigned to @Mcat12 via [this comment](https://github.com/rust-lang/chalk/issues/453#issuecomment-628011487).

**Comment by Mcat12** [comment]
This seems straightforward enough, I'll give it a shot.

@rustbot assign
