### ISSUE TITLE
Crate structure cleanup

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#456]
There are a few different crate structure cleanups we want to do.

* [ ] Move recursive solver out of `chalk-solve`
  - A lot of the functionality here overlaps with `chalk-engine`, so it would be nice try to set up the crate structure in a way that we only need to compile one or the other.
* [ ] Merge chalk-rust-ir into chalk-solve
  - This is a pretty small crate and there's not really a benefit to keeping it split.
* [ ] Move chalk-macros into chalk-engine
  - chalk-macros is also pretty small. This might be a little different, depending on the how the first bullet point goes. But basically, this doesn't need to be all by itself.

This issue has been assigned to @Mcat12 via [this comment](https://github.com/rust-lang/chalk/issues/456#issuecomment-629698312).

**Comment by Mcat12** [comment]
I can take this, though I have a question about "Merge chalk-rust-ir into chalk-solve". Will it need to be moved out again once a common type library is shared with rustc? Keeping it out of chalk-solve would therefore be closer to the target state.

@rustbot claim

**Comment by Mcat12** [comment]
Is the SLG solver wholly contained within `chalk-engine`, or is it also in `chalk-solve`? It may make sense to have a structure where `chalk-engine` provides the shared types between the SLG and recursive solvers. The solvers would be in their own `chalk-slg-solver`/`chalk-recursive-solve` crates and depend on `chalk-engine`. Then `chalk-solve` would depend on all three crates. Does this make sense?

**Comment by jackh726** [comment]
I think @zaharidichev wanted to work on this: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/coinduction.20in.20the.20recursive.20solver.20chalk.23399/near/197735953

**Comment by jackh726** [comment]
But to answer your questions @Mcat12, the types that we need to share are all in `chalk-ir`.

As far as SLG, the core logic is all in`chalk-engine`, but the `Slg` context and aggregate logic is in `chalk-solve`. I was also think that there would be a shared crate that both slg and recursive solvers depend on. And solve depends on both. But I don't really know if about the recursive solver to say how much is actually shared.

**Comment by zaharidichev** [comment]
Yeah I wanted to but life is first come first served :)  So take a stab @Mcat12!  @jackh726  Anything else that I can dig  into (something hard)?

**Comment by Mcat12** [comment]
That's fine, I can unassign myself assuming he's still interested.

Do you know of other issues that might help me learn the codebase? I'm at an "intermediate" level with the codebase, but I found some issues that may be doable. Perhaps you would have a better idea which would be most suitable? #313 #429

@rustbot release-assignment

**Comment by jackh726** [comment]
Let me open a topic on Zulip for a few things people can work on!

**Comment by Mcat12** [comment]
Thanks for the Zulip thread @jackh726 ([link](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/Things.20to.20do))! I'll re-claim this issue; it looks like @zaharidichev will be working on #313.

@rustbot claim

**Comment by Mcat12** [comment]
Based on a [Zulip discussion], we'll keep the recursive solver in chalk-solve for now but still have the "chalk-engine-base" crate which holds the few shared solver types (replacing chalk-macros).

[Zulip discussion]: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/recursive.20solver.20and.20chalk-solve.20seam
