### ISSUE TITLE
create a "generator witness" type

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#504]
As described [in the chalk book](http://rust-lang.github.io/chalk/book/types/rust_types.html#generator-witness-types), we need a generator witness type. More details coming.

This issue has been assigned to @Aaron1011 via [this comment](https://github.com/rust-lang/chalk/issues/504#issuecomment-641548313).

**Comment by Aaron1011** [comment]
Implemented in https://github.com/rust-lang/chalk/pull/593
