### ISSUE TITLE
rename the `Fn` type to `FnPointer`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#507]
The `Fn` type in chalk should be called `FnPointer` or perhaps `FunctionPointer`. Easy refactoring.

This issue has been assigned to @mental32 via [this comment](https://github.com/rust-lang/chalk/issues/507#issuecomment-641558479).

**Comment by nikomatsakis** [comment]
Some other things we should support:

* unsafe fn
* ABI (being added already in a PR)

**Comment by nikomatsakis** [comment]
To add support for unsafe functions will require

* extending the parser to permit `unsafe fn` and `fn`
* adding a field to the `Fn` type
* modifying the unification code
* modifying the support for the built-in `Fn` types, unsafe fns do not implement them

**Comment by nikomatsakis** [comment]
https://github.com/rust-lang/chalk/pull/481 is a good model for most of that

**Comment by nikomatsakis** [comment]
@rustbot assign @mental32

Sorry @mental :)

**Comment by mental32** [comment]
@nikomatsakis No worries, you noticed it quicker than I did :laughing: 

> Some other things we should support:
> 
>     * unsafe fn
> 
>     * ABI (being added already in a PR)

Are these also in the scope of this PR?

**Comment by nikomatsakis** [comment]
Yes @mental32 those are in scope I think

**Comment by nikomatsakis** [comment]
They could be done in distinct PRs

**Comment by mental32** [comment]
Asking since I'm not sure whether the claim would apply there or not but good to know

**Comment by flodiebold** [comment]
We also need the `variadic` flag on function pointers.
