### ISSUE TITLE
Support different trait order in trait object unification

### ISSUE THREAD

**Issue by Areredify** [rust-lang/chalk#510]
Currently when doing unification of trait objects, we check that they are exactly equal, including order of auto traits and associated type clauses. We need to fix that and allow trait objects have any order of where clauses on them. Note that after implementing it some `Unsize` tests should begin to fail, you would need to bless them (and remove "FIXME" comments)

This issue has been assigned to @zaharidichev via [this comment](https://github.com/rust-lang/chalk/issues/510#issuecomment-642025909).

**Comment by zaharidichev** [comment]
@Areredify Looking at it a bit more closely, I wonder what the correct approach might be. Just sort everything before zipping in turn right [here](https://github.com/rust-lang/chalk/blob/master/chalk-ir/src/zip.rs#L119)?  I guess that would necessitate for a lot of types to derive `Ord`. Would that make sense ?

**Comment by Areredify** [comment]
I suggest looking at what rustc does here first (I am not familiar with rustc code for this so I can't really give pointers)

**Comment by scalexm** [comment]
rustc defines an arbitrary « canonical order » for traits in trait objects, and always sort them according to that order during AST conversion.

See: https://github.com/rust-lang/rust/blob/3ddf48053e83f4949d00dcaf6eb8d9e28fc6bb95/src/librustc_typeck/astconv.rs#L1703

**Comment by Areredify** [comment]
We should probably do the same, can't really think of a better way

**Comment by zaharidichev** [comment]
I wonder whether dedup makes sense as well?
