### ISSUE TITLE
Coherence issue with overlapping imps with assoc types

### ISSUE THREAD

**Issue by Areredify** [rust-lang/chalk#515]
Given 
```
trait Iterator {
    type Item;
}

trait Trait {}

impl<T> Trait for T where T: Iterator<Item = u32> {} 
impl<T> Trait for T where T: Iterator<Item = u32> {} 

struct Foo {}
```
we don't throw a coherence error. Adding `impl Iterator for Foo { type Item = u32; }` makes it appear, but it should work without it too.

**Comment by Mcat12** [comment]
Might be related to or fixed by #457?

**Comment by Areredify** [comment]
I doubt it, there is no coinduction involved in this example

**Comment by Mcat12** [comment]
Oh, my bad, mixed up conduction and coherence :sweat_smile:

**Comment by Mcat12** [comment]
I've been looking into this a bit, might as well claim it. It looks like there might be an unexpected floundering and some missing clauses related to AliasEq and the compatible mode.

@rustbot claim
