### ISSUE TITLE
Add callback to get repr data

### ISSUE THREAD

**Issue by Areredify** [rust-lang/chalk#517]
To perform some of wf checks, we need to know whether or not struct has `#[repr(C)]` or `#[repr(packed)]` (only those two). So we need to add a database callback to get that info given an adt id and extend the parser to account for it in ChalkDatabase.

This issue has been assigned to @voidc via [this comment](https://github.com/rust-lang/chalk/issues/517#issuecomment-643694192).

**Comment by voidc** [comment]
Hi everyone! I'm Dominik and I'm interested in getting involved in rustc and chalk development. This seem like a good place to start and get familiar with the code, so I filed a draft pull request (#523).

@rustbot claim
