### ISSUE TITLE
Reduce boilerplate for interned type definitions

### ISSUE THREAD

**Issue by nathanwhit** [rust-lang/chalk#550]
Right now we repeat code [like this](https://github.com/rust-lang/chalk/blob/e7d8893231cda2ea18099d3e0e90d780925ff0b9/chalk-ir/src/lib.rs#L2672-L2705) in at least 4-5 places across `chalk-ir`. This not only creates bloat, making the definitions in`chalk-ir` harder to read, but also makes adding new interned types very tedious. We should find a way to reduce the amount of code duplication and boilerplate here.

**Comment by nikomatsakis** [comment]
Macros or derive might be an option here -- perhaps a trait for interned sequences? Something like that.

**Comment by nathanwhit** [comment]
Closed by #554.
