### ISSUE TITLE
Remove `force_impl_for` in `RustIrDatabase`

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#560]
Now that we handle enums (and other `TypeName`s), we don't need this on the rustc side anymore.

This issue has been assigned to @vandenheuvel via [this comment](https://github.com/rust-lang/chalk/issues/560#issuecomment-663269528).

**Comment by Mcat12** [comment]
Does it make sense to tag this as a good first issue?

**Comment by vandenheuvel** [comment]
@jackh726 could you close this?
