### ISSUE TITLE
Add a "notation" section to the glossary of the book

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#561]
While we talk about bound vars, inference vars, and placeholders in different parts of the book and sometimes introduce notation, we should have a single consolidated section in the glossary to specifically mention some notation, such as:
```
?0 - Inference Var
^0, ^1.0 - Bound var
!0 - Placeholder
A :- B - A if B
```

Maybe others

**Comment by josh65536** [comment]
Could notation be its own appendix?
