### ISSUE TITLE
Use `dyn Solver` instead of `S: Solver` in `chalk_solve`

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#562]
See https://github.com/rust-lang/chalk/pull/546#discussion_r448618711

**Comment by zaharidichev** [comment]
I will take this one, if there are no objections

**Comment by zaharidichev** [comment]
@jackh726 I might be incorrect but it seems we cannot have the solver trait as a dyn where we would ideally want it: 

```
the trait `solve::Solver` cannot be made into an object
consider moving `solve_limited` to another trait
consider moving `solve_multiple` to another traitrustc(E0038)
```

**Comment by jackh726** [comment]
Haha, yep that's because of the `should_continue`. @nikomatsakis any ideas here?

**Comment by Mcat12** [comment]
Would adding `where Self: Sized` to each method be possible? That should make the trait object-safe.

**Comment by nathanwhit** [comment]
> Would adding `where Self: Sized` to each method be possible? That should make the trait object-safe.

That wouldn't be enough to make it object-safe, unfortunately. The trait is also not object-safe because it takes a generic parameter, which seems like the harder problem to solve.

**Comment by nikomatsakis** [comment]
> The trait is also not object-safe because it takes a generic parameter, which seems like a harder problem to solve.

This is not correct. A trait can have generic parameters and still be dyn safe.

I think adding `where Self: Sized` could work though I indeed would probably just change to `dyn` arguments:

```rust
pub trait Solver<I: Interner> where
    Self: Debug, {
    fn solve(
        &mut self, 
        program: &dyn RustIrDatabase<I>, 
        goal: &UCanonical<InEnvironment<Goal<I>>>
    ) -> Option<Solution<I>>;
    fn solve_limited(
        &mut self, 
        program: &dyn RustIrDatabase<I>, 
        goal: &UCanonical<InEnvironment<Goal<I>>>, 
        should_continue: &dyn Fn() -> bool
    ) -> Option<Solution<I>>;
    fn solve_multiple(
        &mut self, 
        program: &dyn RustIrDatabase<I>, 
        goal: &UCanonical<InEnvironment<Goal<I>>>, 
        f: &mut dyn FnMut(SubstitutionResult<Canonical<ConstrainedSubst<I>>>, bool) -> bool
    ) -> bool;
}
```

This will require modifying the callers to add `&|| ...` and `&mut || ...`, unfortunately.
