### ISSUE TITLE
Decide whether the program clauses code should work on canonical or instantiated goals

### ISSUE THREAD

**Issue by flodiebold** [rust-lang/chalk#568]
Currently, the SLG solver and the recursive solver disagree about what to pass to the program clauses code: The SLG solver instantiates the goal and then calls the program clauses code for it; the recursive solver calls it with the canonical goal. (This means that in the same goal, there will be either inference variables or bound variables depending on the solver.) There are advantages to both, but we should decide which way to go because it complicates the program clauses code to handle both.

**Comment by nikomatsakis** [comment]
Sigh. I'm trying to remember why, but I know that I *initially* thought that the SLG solver was correct (we should invoke on instantiated goals) and I changed my mind at some point to think that the recursive solver was handling it more correctly.
