### ISSUE TITLE
Updating rust to chalk 0.19.0 requires chalk-integration to be published to crates.io

### ISSUE THREAD

**Issue by vandenheuvel** [rust-lang/chalk#586]
I am trying to upgrade rust to use chalk 0.19.0. Rust uses chalk-integration's `SolverChoice` which used to be in chalk-solve until https://github.com/rust-lang/chalk/commit/0847162dce483d65730eebdebca39233dff4518b. It seems to me that this requires publishing chalk-integration to crates.io.

**Comment by flodiebold** [comment]
You don't want to use chalk-integration, that's the integration test. You should rather directly construct the SLG solver instead of going through `SolverChoice`.
