### ISSUE TITLE
Regression for well known trait impls for builtin types

### ISSUE THREAD

**Issue by jackh726** [rust-lang/chalk#590]
So, this regression happened sometime between 0.14 and 0.20.

Basically, if we have a goal like
```
Canonical {
  value: InEnvironment {
    environment: Env([]),
    goal: Implemented(Ty(^0.0): TraitId(DefId(2:1942 ~ core[d282]::marker[0]::Sized[0]))),
  },
  binders: [U0 with kind integer type],
}
```
then we don't generate the clause for `Sized` impl (at least with SLG).

We pass `Implemented(Ty(?0i): TraitId(DefId(2:1942 ~ core[d282]::marker[0]::Sized[0])))` to `program_clauses_for_goal`; the `?0i` self type is not covered in `add_sized_program_clauses`. ~~I haven't tested `Copy`/`Clone`, but I'm almost certain the same problem occurs.~~ Edit: forgot that these are in libcore, so aren't builtin for ints/floats.

**Comment by flodiebold** [comment]
I think we would have floundered on this before #555, but now it's actually hitting the built-in clauses code which doesn't handle it.

**Comment by jackh726** [comment]
Well, we used to be able to solve that goal fine in SLG (I found this when updating the rustc integration, because lots of tests there fail now)

Yeah, this should be a fairly simple fix, but its actually a pretty big issue.

**Comment by flodiebold** [comment]
My guess is it worked because rustc tried again later when the variable was resolved. Now Chalk will say the goal can't be solved.
