### ISSUE TITLE
Support extern opaque types.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/chalk#595]
```rust
#![feature(extern_types)]

extern "C" {
    type A;
    fn foo() -> Box<A>;
    fn bar();
}

impl A {
    fn bar(&self) {
        unsafe {bar()};
    }
}

fn main() {
    let a = unsafe { foo() } ;
    a.bar();
}
```
This code compiles fine in rustc, but rust-analyzer gives `Box<{unknown}>` inlay hint to a.

**Comment by jackh726** [comment]
While not technically "built-in", I think this falls under #368, so I'm gonna link this there.

Overall, I think this should be pretty easy. I *think* we really only need to add an extra variant to `TypeName`. Other than that, we won't add any clauses for `Sized`/`Copy`/`Clone` traits.

**Comment by memoryleak47** [comment]
I'll try this one.

**Comment by jackh726** [comment]
Ah right, I can't do that.

**Comment by crlf0710** [comment]
Thanks! Hopefully this will help solve https://github.com/rust-analyzer/rust-analyzer/issues/4150 .
