### ISSUE TITLE
Add static lifetime

### ISSUE THREAD

**Issue by detrumi** [rust-lang/chalk#610]
Add support for `'static` lifetime (also called `ReStatic`)

[discussion during last meeting](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/meeting.202020-09-15/near/210186364)
[branch that made a start on this](https://github.com/rust-lang/chalk/compare/master...nikomatsakis:outlives)

**Comment by Aaron1011** [comment]
@detrumi Are you still working on this?

**Comment by detrumi** [comment]
I made [a start](https://github.com/rust-lang/chalk/compare/master...detrumi:static-lifetimes) on it, though I think @jackh726 is currently finishing it.

**Comment by detrumi** [comment]
Implemented in #617
