### ISSUE TITLE
Refactor Fold to take by value

### ISSUE THREAD

**Issue by detrumi** [rust-lang/chalk#642]
Currently, the [`Folder` trait](https://github.com/rust-lang/chalk/blob/80747d9147a77dae4e16b7abcfa2e169b036cb85/chalk-ir/src/fold.rs#L66) takes folded values by reference. As part of the [shared type library plan](https://github.com/rust-lang/wg-traits/issues/16), the fold traits should take their folded values by value, to match [the `TypeFolder`](https://github.com/rust-lang/rust/blob/ffe52882ed79be67344dd6085559e308241e7f60/compiler/rustc_middle/src/ty/fold.rs#L45) trait in rustc.

For example, this
```
fn fold_ty(&mut self, ty: &Ty<I>, outer_binder: DebruijnIndex) -> Fallible<Ty<TI>>
```
should be changed to this:
```
fn fold_ty(&mut self, ty: Ty<I>, outer_binder: DebruijnIndex) -> Fallible<Ty<TI>>
```
Same thing with the other folding functions.
Lastly, code that calls folding functions should pass the values by value, instead of by reference.

**Comment by lnicola** [comment]
Should the `Fold` implementations and trait be updated to also pass by value, or can they copy/clone?

```rust
impl<I: Interner, TI: TargetInterner<I>> Fold<I, TI> for Const<I> {
    type Result = Const<TI>;

    fn fold_with<'i>(
        &self,
        folder: &mut dyn Folder<'i, I, TI>,
        outer_binder: DebruijnIndex,
    ) -> Fallible<Self::Result>
    where
        I: 'i,
        TI: 'i,
    {
        folder.fold_const(self /* <-- this */, outer_binder)
    }
}
```

`Copy` might work, since they all use interned values.

**Comment by detrumi** [comment]
Yes, because `fold_with` should also take `self` by value

**Comment by lnicola** [comment]
Sorry for the noob questions, but is it all right to add `Clone` bounds to the `T` in `u_canonicalize` and `map_from_canonical`? They seem to call `fold_with` on borrowed values.

**Comment by detrumi** [comment]
> Sorry for the noob questions, but is it all right to add `Clone` bounds to the `T` in `u_canonicalize` and `map_from_canonical`? They seem to call `fold_with` on borrowed values.

You mean the calls like this?
```
            .fold_with(
                &mut UMapFromCanonical {
                    interner,
                    universes: self,
                },
                DebruijnIndex::INNERMOST,
            )
```
I think you can remove the `&mut` and have it work, no need to clone here.

**Comment by lnicola** [comment]
I tried to make this work, but couldn't manage. I left some notes in https://github.com/rust-lang/chalk/pull/644#issuecomment-734952970 and the branch is up, in case someone else wants to try.
