### ISSUE TITLE
RELEASES.md has no information on the automated releases

### ISSUE THREAD

**Issue by AzureMarker** [rust-lang/chalk#665]
Since adding automated releases, each new entry in [RELEASES.md] is empty. Can we put links to the commits or PRs merged?

[RELEASES.md]: https://github.com/rust-lang/chalk/blob/master/RELEASES.md

**Comment by jackh726** [comment]
@pksunkara any ideas?

**Comment by pksunkara** [comment]
You can add a command to do that. Currently it's just bash scripting for writing a new line
