### ISSUE TITLE
CI Publish job using Mac runner

### ISSUE THREAD

**Issue by AzureMarker** [rust-lang/chalk#721]
I noticed while putting together #720 that the publish job is run under `macos-latest`. @pksunkara is this intentional? I don't see why we can't use a Linux runner, since those are more plentiful/standard.

**Comment by pksunkara** [comment]
I had some issues getting the `sed` working on Ubuntu.

**Comment by AzureMarker** [comment]
Since we're not using the sed anymore, I'll try switching it to ubuntu.
