### ISSUE TITLE
Missing a fallback rule for unselected projections?

### ISSUE THREAD

**Issue by scalexm** [rust-lang/chalk#85]
So given:
```rust
trait Foo {
    type Item;
}
```
then the goal `forall<T> { if (T: Foo, InScope(Foo)) { T: Foo<Item = T::Item> } }` or equivalently, `forall<T> { if (T: Foo, InScope(Foo)) { <T as Foo>::Item = T::Item } }` answers `No possible solution`.

It seems like a "fallback" rule (i.e. which would normalize `<T as Foo>::Item` to `T::Item`) is missing.

**Comment by nikomatsakis** [comment]
I have to admit I didn't look or think about unselected projections very carefully. I would not expect a normalize rule, more like some equivalent to `ProjectionEq`.
