### ISSUE TITLE
Const generics

### ISSUE THREAD

**Issue by varkor** [rust-lang/chalk#98]
With work on [const generics underway in rustc](https://github.com/rust-lang/rust/issues/44580), we'll want to make sure Chalk also supports them.

I've started looking into this [here](https://github.com/rust-lang-nursery/chalk/compare/master...varkor:const-generics), starting off [by extending `ParameterKind`](https://github.com/varkor/chalk/blob/eba01aad7341d0baf47ba5f259247f0befef8d1f/chalk-parse/src/ast.rs#L58-L62) and filling in things from there. I'll give an update when progress is a little further along.

**Comment by Mcat12** [comment]
#393 has been merged, can this be closed?

**Comment by nikomatsakis** [comment]
I guess so -- I don't think we've completed the story here, but at the same time I think we need a fresh tracking issue with more detail, and that issue may even want to live in the wg-traits repository.
